name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8.0
      uses: actions/setup-java@v1
      with:
        java-version: 8.0
    - name: Build with Gradle
      run: ./gradlew build
